metadata:
  keywords:
    - 'English dark (dracula) theme for beamer'
documentclass: beamer
pdf-engine: xelatex
highlight-style: /home/hos/.config/pandoc/highlight/dracula-beamer.theme
variables:
  aspectratio: 169
#  background-image: /home/hos/.config/pandoc/background/manjaro-default-adapta-lockscreen.jpg
  header-includes:
    - \usepackage{/home/hos/.config/pandoc/defaults/beamer/en-dracula}
    - \themeconfig{shadow=no, shade=yes, three=yes, sidebar=yes}

filters:
  - /home/hos/.config/pandoc/filters/en-today.lua
