metadata:
  keywords:
    - 'English dark (manjaro) theme for beamer'
  documentclass: beamer
pdf-engine: xelatex
highlight-style: /home/hos/.config/pandoc/highlight/hybrid-light.theme
variables:
  aspectratio: 169
#  background-image: /home/hos/.config/pandoc/background/manjaro-default-adapta-lockscreen.jpg
  header-includes:
    - \usepackage{/home/hos/.config/pandoc/defaults/beamer/en-ubuntu}
    - \themeconfig{shadow=yes, shade=yes, three=yes, sidebar=yes}

filters:
  - /home/hos/.config/pandoc/filters/en-today.lua
